### ISSUE TITLE
Why is slug required for getTracking?

### ISSUE THREAD

**Issue by xinghul** [AfterShip/aftership-sdk-nodejs#73]
When creating a tracking, the slug is optional, and Aftership will create the tracking with inferred slug value, which works great.

But when getting a tracking, why is slug required? more specifically:
- Sometimes the user does not know the "correct" slug when trying to get tracking.
- Why can't Aftership infer a slug name in this case?

**Comment by Bossa573** [comment]
Hello, 
because a slug, a tracking number (and together with additional fields) forms a unique key of a tracking object,
for retrieving a single tracking, you must have to use either an ID, 
or a slug + tracking number (and together with additional fields for some couriers)

and for creating a tracking, if you do not provide a slug, the system will try to detect the courier automatically according to the courier setting under your account.

you can also refer to the API documentation: https://developers.aftership.com/
thank you very much

**Comment by xinghul** [comment]
hi, I guess my question is, when retrieving a single tracking, can the system detect the slug when only a tracking number is provided?

**Comment by Bossa573** [comment]
because `tracking_number` is not a key field in an account - not unique, it can be more than 1 tracking with the same `tracking_number` in your account, it's not possible to retrieve a single tracking only with the tracking number - the system cannot "guess" which tracking you want to retrieve, and even the system detect the tracking number format and try to get a tracking number, the UX would not be desirable at all.

**Comment by Bossa573** [comment]
if you want to search all occurrences which matching an input `tracking_number` , you should use `listTrackings` to perform the query instead

**Comment by Bossa573** [comment]
for such case, please use listTrackings, 
because semantically you are `querying` an tracking resourrce, 
for getting a single resource, a `key` must be provided, no matter tracking ID or combination of fields (tracking number, slug, etc) which form a `key`.

This would not be changed anyway as this is breaking the semantical design of the restful API  fundamentally.
